<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class VALIDACIONES
    Inherits System.Windows.Forms.Form

    'Form reemplaza a Dispose para limpiar la lista de componentes.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Requerido por el Diseñador de Windows Forms
    Private components As System.ComponentModel.IContainer

    'NOTA: el Diseñador de Windows Forms necesita el siguiente procedimiento
    'Se puede modificar usando el Diseñador de Windows Forms.  
    'No lo modifique con el editor de código.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.Label4 = New System.Windows.Forms.Label()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.Label7 = New System.Windows.Forms.Label()
        Me.DTP1 = New System.Windows.Forms.DateTimePicker()
        Me.TXTAPELLIDO = New System.Windows.Forms.MaskedTextBox()
        Me.TXT_CI = New System.Windows.Forms.MaskedTextBox()
        Me.TXT_NOMBRE = New System.Windows.Forms.TextBox()
        Me.TXT_TEL = New System.Windows.Forms.TextBox()
        Me.TXT_MAIL = New System.Windows.Forms.TextBox()
        Me.TXT_CONTRASEÑA = New System.Windows.Forms.TextBox()
        Me.BTN_AGREGAR = New System.Windows.Forms.Button()
        Me.BTN_VER = New System.Windows.Forms.Button()
        Me.BTN_FIN = New System.Windows.Forms.Button()
        Me.SuspendLayout()
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.Location = New System.Drawing.Point(86, 42)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(79, 20)
        Me.Label1.TabIndex = 0
        Me.Label1.Text = "NOMBRE"
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label2.Location = New System.Drawing.Point(92, 85)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(88, 20)
        Me.Label2.TabIndex = 1
        Me.Label2.Text = "APELLIDO"
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label3.Location = New System.Drawing.Point(86, 121)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(94, 20)
        Me.Label3.TabIndex = 2
        Me.Label3.Text = "TELÉFONO"
        '
        'Label4
        '
        Me.Label4.AutoSize = True
        Me.Label4.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label4.Location = New System.Drawing.Point(86, 160)
        Me.Label4.Name = "Label4"
        Me.Label4.Size = New System.Drawing.Size(105, 20)
        Me.Label4.TabIndex = 3
        Me.Label4.Text = "FECHA NAC."
        '
        'Label5
        '
        Me.Label5.AutoSize = True
        Me.Label5.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label5.Location = New System.Drawing.Point(110, 208)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(75, 20)
        Me.Label5.TabIndex = 4
        Me.Label5.Text = "CEDULA"
        '
        'Label6
        '
        Me.Label6.AutoSize = True
        Me.Label6.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label6.Location = New System.Drawing.Point(128, 249)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(63, 20)
        Me.Label6.TabIndex = 5
        Me.Label6.Text = "E-MAIL"
        '
        'Label7
        '
        Me.Label7.AutoSize = True
        Me.Label7.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label7.Location = New System.Drawing.Point(72, 291)
        Me.Label7.Name = "Label7"
        Me.Label7.Size = New System.Drawing.Size(119, 20)
        Me.Label7.TabIndex = 6
        Me.Label7.Text = "CONTRASEÑA"
        '
        'DTP1
        '
        Me.DTP1.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.DTP1.Format = System.Windows.Forms.DateTimePickerFormat.[Short]
        Me.DTP1.Location = New System.Drawing.Point(235, 154)
        Me.DTP1.Name = "DTP1"
        Me.DTP1.Size = New System.Drawing.Size(215, 26)
        Me.DTP1.TabIndex = 7
        '
        'TXTAPELLIDO
        '
        Me.TXTAPELLIDO.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TXTAPELLIDO.Location = New System.Drawing.Point(235, 79)
        Me.TXTAPELLIDO.Name = "TXTAPELLIDO"
        Me.TXTAPELLIDO.Size = New System.Drawing.Size(215, 26)
        Me.TXTAPELLIDO.TabIndex = 8
        '
        'TXT_CI
        '
        Me.TXT_CI.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TXT_CI.Location = New System.Drawing.Point(235, 202)
        Me.TXT_CI.Name = "TXT_CI"
        Me.TXT_CI.Size = New System.Drawing.Size(215, 26)
        Me.TXT_CI.TabIndex = 9
        '
        'TXT_NOMBRE
        '
        Me.TXT_NOMBRE.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TXT_NOMBRE.Location = New System.Drawing.Point(235, 36)
        Me.TXT_NOMBRE.Name = "TXT_NOMBRE"
        Me.TXT_NOMBRE.Size = New System.Drawing.Size(215, 26)
        Me.TXT_NOMBRE.TabIndex = 10
        '
        'TXT_TEL
        '
        Me.TXT_TEL.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TXT_TEL.Location = New System.Drawing.Point(235, 111)
        Me.TXT_TEL.Name = "TXT_TEL"
        Me.TXT_TEL.Size = New System.Drawing.Size(165, 26)
        Me.TXT_TEL.TabIndex = 12
        '
        'TXT_MAIL
        '
        Me.TXT_MAIL.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TXT_MAIL.Location = New System.Drawing.Point(235, 243)
        Me.TXT_MAIL.Name = "TXT_MAIL"
        Me.TXT_MAIL.Size = New System.Drawing.Size(165, 26)
        Me.TXT_MAIL.TabIndex = 13
        '
        'TXT_CONTRASEÑA
        '
        Me.TXT_CONTRASEÑA.Font = New System.Drawing.Font("Microsoft Sans Serif", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.TXT_CONTRASEÑA.Location = New System.Drawing.Point(235, 285)
        Me.TXT_CONTRASEÑA.Name = "TXT_CONTRASEÑA"
        Me.TXT_CONTRASEÑA.PasswordChar = Global.Microsoft.VisualBasic.ChrW(42)
        Me.TXT_CONTRASEÑA.Size = New System.Drawing.Size(165, 26)
        Me.TXT_CONTRASEÑA.TabIndex = 14
        '
        'BTN_AGREGAR
        '
        Me.BTN_AGREGAR.Location = New System.Drawing.Point(103, 358)
        Me.BTN_AGREGAR.Name = "BTN_AGREGAR"
        Me.BTN_AGREGAR.Size = New System.Drawing.Size(82, 38)
        Me.BTN_AGREGAR.TabIndex = 15
        Me.BTN_AGREGAR.Text = "AGREGAR"
        Me.BTN_AGREGAR.UseVisualStyleBackColor = True
        '
        'BTN_VER
        '
        Me.BTN_VER.Location = New System.Drawing.Point(244, 358)
        Me.BTN_VER.Name = "BTN_VER"
        Me.BTN_VER.Size = New System.Drawing.Size(82, 38)
        Me.BTN_VER.TabIndex = 16
        Me.BTN_VER.Text = "VER"
        Me.BTN_VER.UseVisualStyleBackColor = True
        '
        'BTN_FIN
        '
        Me.BTN_FIN.Image = Global.Primer_proyecto_2023.My.Resources.Resources.thewindowsclosedtheprogram_theoutput_11873
        Me.BTN_FIN.ImageAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.BTN_FIN.Location = New System.Drawing.Point(377, 358)
        Me.BTN_FIN.Name = "BTN_FIN"
        Me.BTN_FIN.Size = New System.Drawing.Size(88, 38)
        Me.BTN_FIN.TabIndex = 17
        Me.BTN_FIN.Text = "FIN"
        Me.BTN_FIN.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.BTN_FIN.UseVisualStyleBackColor = True
        '
        'VALIDACIONES
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(800, 450)
        Me.Controls.Add(Me.BTN_FIN)
        Me.Controls.Add(Me.BTN_VER)
        Me.Controls.Add(Me.BTN_AGREGAR)
        Me.Controls.Add(Me.TXT_CONTRASEÑA)
        Me.Controls.Add(Me.TXT_MAIL)
        Me.Controls.Add(Me.TXT_TEL)
        Me.Controls.Add(Me.TXT_NOMBRE)
        Me.Controls.Add(Me.TXT_CI)
        Me.Controls.Add(Me.TXTAPELLIDO)
        Me.Controls.Add(Me.DTP1)
        Me.Controls.Add(Me.Label7)
        Me.Controls.Add(Me.Label6)
        Me.Controls.Add(Me.Label5)
        Me.Controls.Add(Me.Label4)
        Me.Controls.Add(Me.Label3)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.Label1)
        Me.Name = "VALIDACIONES"
        Me.Text = "VALIDACIONES"
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents Label1 As Label
    Friend WithEvents Label2 As Label
    Friend WithEvents Label3 As Label
    Friend WithEvents Label4 As Label
    Friend WithEvents Label5 As Label
    Friend WithEvents Label6 As Label
    Friend WithEvents Label7 As Label
    Friend WithEvents DTP1 As DateTimePicker
    Friend WithEvents TXTAPELLIDO As MaskedTextBox
    Friend WithEvents TXT_CI As MaskedTextBox
    Friend WithEvents TXT_NOMBRE As TextBox
    Friend WithEvents TXT_TEL As TextBox
    Friend WithEvents TXT_MAIL As TextBox
    Friend WithEvents TXT_CONTRASEÑA As TextBox
    Friend WithEvents BTN_AGREGAR As Button
    Friend WithEvents BTN_VER As Button
    Friend WithEvents BTN_FIN As Button
End Class
